Todo list
kubilaycaglayan/todo-list pull request #1
Opened 2020-07-06 12:22 UTC by kubilaycaglayan

2020-07-13 18:21 UTC, shloch requested changes
## Hello @kubilaycaglayan , 

Great job

### [required changes]

You need to do form controls to make sure empty forms cannot be submitted
I think that's basically what needs to be done
![todo](https://user-images.githubusercontent.com/40712459/87338925-c5c63680-c53d-11ea-9e93-dba1f33bf0dc.gif)

![todo2](https://user-images.githubusercontent.com/40712459/87338956-cd85db00-c53d-11ea-8f24-d2659773e933.gif)

Happy coding

2020-07-14 07:54 UTC, javitocor commented
We have added validation for the forms as requested.

2020-07-14 08:04 UTC, bellom approved these changes
## Hi Team :clap: 

**Great work making all the necessary corrections from the previous review.**

## Congratulation :+1:  
_Go ahead and merge to dev and don't forget to submit project completion form.
Good luck in the next project :slightly_smiling_face:_ 

**Best,**

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

2020-07-14 08:04 UTC, bellom commented on src/models/events.js
> +      window.alert('You need to fill the input field!');
I trust you can do this 👇  before merging, `required` is already doing the job
`This should be production code, we shouldn't have `alert`, please remove the `alert`.`

2020-07-14 08:04 UTC, bellom commented on src/models/events.js
> +      window.alert('You missed fill up one or more fields!');
I trust you can do this 👇  before merging, `required` is already doing the job
`This should be production code, we shouldn't have `alert`, please remove the `alert`.`

2020-07-14 11:50 UTC, merged